
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Sep 01 21:45:06 CEST 2024
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int AND_LOGICA = 5;
  public static final int NUMERO = 36;
  public static final int ALTENATIVAS = 26;
  public static final int CASO = 20;
  public static final int MULT = 4;
  public static final int TIPO = 33;
  public static final int AUTO_INCREMENTO = 3;
  public static final int ENTERO = 23;
  public static final int SI = 31;
  public static final int TWO_POINTS = 14;
  public static final int CONSTANTE = 21;
  public static final int IDENTIFICADOR = 35;
  public static final int SINO = 32;
  public static final int DEVUELVE = 30;
  public static final int ESCRIBE_ENT = 25;
  public static final int MIENTRAS = 27;
  public static final int PLUS = 2;
  public static final int ASSIGN = 18;
  public static final int CORTE = 22;
  public static final int EOF = 0;
  public static final int OPEN_KEY = 10;
  public static final int CLOSE_KEY = 11;
  public static final int EQUAL = 16;
  public static final int error = 1;
  public static final int ASSIGN_SUMA = 17;
  public static final int SEMI_COLON = 12;
  public static final int NEGACION = 15;
  public static final int CLOSE_BRACKET = 7;
  public static final int ESCRIBE = 24;
  public static final int OPEN_BRACKET = 6;
  public static final int PORDEFECTO = 28;
  public static final int OPEN_PARENTHESIS = 8;
  public static final int COLON = 13;
  public static final int VACIO = 34;
  public static final int LOWER_THAN = 19;
  public static final int STRING = 37;
  public static final int CLOSE_PARENTHESIS = 9;
  public static final int principal = 29;
}

